In [33]:
import numpy as np

In [34]:
benimListem = [20,30,40]

In [35]:
type(benimListem)

list

In [36]:
np.array(benimListem)

array([20, 30, 40])

In [37]:
matrixListesi = [[10,20,30],[20,30,40],[50,60,70]]

In [38]:
matrixListesi

[[10, 20, 30], [20, 30, 40], [50, 60, 70]]

In [39]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [50, 60, 70]])

arange

In [40]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

zeros

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [53]:
np.ones(5)
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

linspace

In [56]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [57]:
# eye
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

random

In [59]:
np.random.randn(4)

array([-1.04493299, -0.08775659, -0.00615029, -0.58049593])

In [63]:
np.random.randn(2,2)

array([[ 0.8431502 , -0.19056255],
       [-0.62878489,  1.79765326]])

In [67]:
np.random.randint(1,10)

1

In [69]:
numpyDizi = np.arange(20)
numpyDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
randomDizi = np.random.randint(0,100,30)
randomDizi

array([57, 30, 51, 28, 24,  9, 82, 45, 66,  4, 95, 35, 66, 88, 60, 52, 79,
        9, 26, 97, 90, 13, 40, 76, 70,  0, 28,  8, 81, 30])

numpy Dizi Methodları

In [73]:
numpyDizi.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [75]:
randomDizi.reshape(5,6)

array([[57, 30, 51, 28, 24,  9],
       [82, 45, 66,  4, 95, 35],
       [66, 88, 60, 52, 79,  9],
       [26, 97, 90, 13, 40, 76],
       [70,  0, 28,  8, 81, 30]])

In [76]:
numpyDizi.max()

19

In [77]:
randomDizi.max()

97

In [78]:
randomDizi.argmin()

25

In [79]:
randomDizi.argmax()

19

In [81]:
numpyDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [83]:
numpyDiziReshape = numpyDizi.reshape(5,4)
numpyDiziReshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])