In [1]:
import numpy as np

In [2]:
npDizi = np.arange(0,15)

In [3]:
npDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
npDizi[5]

5

In [6]:
npDizi[3:5]

array([3, 4])

In [11]:
npDizi[3:8] = -5   
# 3 ve 8 arasındaki bütün değerler -5 oldu

In [13]:
npDizi

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [15]:
npDizi1 = np.arange(0,24)

In [17]:
npDizi1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
sliceDizi = npDizi1[4:9]

In [26]:
sliceDizi

array([4, 5, 6, 7, 8])

In [29]:
sliceDizi[:] = 120002
sliceDizi

array([120002, 120002, 120002, 120002, 120002])

matrix

In [32]:
benimListe = [[10,20,30],[20,30,40],[40,50,60]]
ornekMatrixDizisi = np.array(benimListe)

In [33]:
benimListe

[[10, 20, 30], [20, 30, 40], [40, 50, 60]]

In [34]:
benimListe[1][2]

40